# Generated by Django 5.2.7 on 2025-10-15 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventoryentry',
            new_name='inventory_i_scanned_efeded_idx',
            old_name='measurement_scanned_412d0a_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryentry',
            new_name='inventory_i_scenari_c2eba0_idx',
            old_name='measurement_scenari_b2227e_idx',
        ),
    ]
